# Generated by Django 5.2.2 on 2025-06-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaWeb', '0003_alter_useravatar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravatar',
            name='apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='useravatar',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
